name: Github Tests

on:
  push:
    branches:
      - '!stable'
      - '!poggit'
    paths:
      - '**.php'
      - '.github/workflows/*'
      - 'test/github/*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  get-php:
    name: Download PHP
    runs-on: ubuntu-22.04
    if: ${{ !github.event.pull_request.draft }}

    steps:
      - uses: actions/checkout@v3
      - name: Check for PHP cache
        id: php-cache
        uses: actions/cache@v3
        with:
          path: "./bin"
          key: "php-cache-${{ hashFiles('./test/github/get-php.sh') }}"

      - name: Download PHP
        if: steps.php-cache.outputs.cache-hit != 'true'
        run: ./test/github/get-php.sh

  code-style:
    name: Code Style Checks
    needs: get-php
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Restore PHP cache
        id: php-cache
        uses: actions/cache@v3
        with:
          path: "./bin"
          key: "php-cache-${{ hashFiles('./test/github/get-php.sh') }}"

      - name: Prefix PHP to PATH
        run: echo "$(pwd)/bin/php7/bin" >> $GITHUB_PATH

      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php

      - name: Restore Composer package cache
        id: composer-cache-php-cs-fixer
        uses: actions/cache@v3
        with:
          path: |
            ./tools/php-cs-fixer/vendor
          key: "composer-v3-cache-php-cs-fixer-${{ hashFiles('./tools/php-cs-fixer/composer.lock') }}"
          restore-keys: |
            composer-v3-cache-php-cs-fixer-
      - name: Install Composer dependencies
        if: steps.composer-cache-php-cs-fixer.outputs.cache-hit != 'true'
        run: php composer.phar install -d tools/php-cs-fixer --no-interaction

      - name: Save Composer package cache
        if: steps.composer-cache-php-cs-fixer.outputs.cache-hit != 'true'
        id: composer-cache-save
        uses: actions/cache/save@v3
        with:
          path: |
            ./tools/php-cs-fixer/vendor
          key: "composer-v3-cache-php-cs-fixer-${{ hashFiles('./tools/php-cs-fixer/composer.lock') }}"

      - name: Run PHP-CS-Fixer
        run: ./tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run --diff --ansi

  analysis:
    name: PHPStan
    needs: get-php
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Restore PHP cache
        id: php-cache
        uses: actions/cache@v3
        with:
          path: "./bin"
          key: "php-cache-${{ hashFiles('./test/github/get-php.sh') }}"

      - name: Prefix PHP to PATH
        run: echo "$(pwd)/bin/php7/bin" >> $GITHUB_PATH

      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php

      - name: Restore Composer package cache
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/composer/files
            ~/.cache/composer/vcs
            ./vendor
          key: "composer-v3-cache-${{ hashFiles('./composer.lock') }}"
          restore-keys: |
            composer-v3-cache-
      - name: Install Composer dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: php composer.phar install --no-interaction

      - name: Save Composer package cache
        if: steps.composer-cache.outputs.cache-hit != 'true'
        id: composer-cache-save
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cache/composer/files
            ~/.cache/composer/vcs
            ./vendor
          key: "composer-v3-cache-${{ hashFiles('./composer.lock') }}"

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze --no-progress --memory-limit=2G --error-format=github
